swagger:
  # 注意：这里要扫描实现类的包路径
  base-package: com.liuwq.service.weixin.impl
  title: 微信服务接口title
  description: 微信服务接口description
  version: 1.1
  terms-of-service-url: www.baidu.com
  contact:
    name: liuwq
    email: 87268782@qq.com
    url: www.baidu.com
  enabled: true
