swagger:
  # 注意：这里要扫描实现类的包路径
  base-package: com.liuwq.service.member.controller
  title: 会员服务接口title
  description: 会员服务接口description
  version: 1.1
  terms-of-service-url: www.baidu.com
  contact:
    name: liuwq
    email: 87268782@qq.com
    url: www.baidu.com
  enabled: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

feign:
  hystrix:
    enabled: true

# 这里优先级小于远程配置
#project:
#  env: 22